name: anderson_crm_flutter
description: "Flutter replacement for the Vue CRM"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  dio: ^5.4.0
  device_info_plus: ^9.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.0
  intl: ^0.18.1
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  crypto: ^3.0.3
  encrypt: ^5.0.1
  cron: ^0.5.0
  web_socket_channel: ^3.0.3
  image_picker: ^1.0.4
  open_file: ^3.3.2
  permission_handler: ^11.1.0
  file_picker: ^10.3.3
  dart_jsonwebtoken: ^2.17.0
  provider: ^6.1.1
  
  powersync: ^1.16.1
  
  # sqlite3: ^2.4.6
  # sqlite_async: ^0.12.2 
  
  # Standard dependencies
  path_provider: ^2.1.4
  path: ^1.9.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  jose: ^0.3.4

  # Web plugins
  flutter_web_plugins:
    sdk: flutter
  
  cookie_jar: ^4.0.8          
  dio_cookie_manager: ^3.1.1  

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
